### ISSUE TITLE
Use more suitable override in RecursiveAstVisitor

### ISSUE THREAD

**Issue by shorben07** [lulupointu/lint_no_list_tutorial_solution#1]
Lint rule does not work if `List` is returned from method without variable assignment, for example:
```
List<String> myMethod() {
return List.filled(3, 'hi');
}
```
On of the solutions is to use `visitInstanceCreationExpression` override:
```
  @override
  void visitInstanceCreationExpression(InstanceCreationExpression node) {
    onVisitInstanceCreationExpression(node);
    super.visitInstanceCreationExpression(node);
  }
```

**Comment by lulupointu** [comment]
True but this is actually a feature. I want to allow a List return type in order to be able to directly give this method to a Widget attribute for example. This List will not be able to be manipulated because it would not be able to be stored (the l'int would catch it), so I think this is a good middle ground.
Depends on what you want to do 😉

**Comment by shorben07** [comment]
Makes sense. Thanks for the explanation!
